apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zuu62jdym-go
  janus-idp.io/tekton: zuu62jdym-go
  backstage.io/kubernetes-id: zuu62jdym-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zuu62jdym-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
